### ISSUE TITLE
tarantool-python 1.6.2 vs tarantool 1.10: exx badly formed hexadecimal UUID string

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool-python#101]
I thought that the problem with UUID format was fixed in 1.6.2, but it still reproduces

**Comment by Totktonada** [comment]
@racktear Reproducer?

**Comment by alg1973** [comment]
Where is original issue?

**Comment by racktear** [comment]
Maybe there is no ticket, but I recall with certainty that it's been reported at least in one of the chats. Anyway, it shouldn't be a stopper, because the problem is trivial to verify: just run the test suite with latest tarantool

**Comment by Totktonada** [comment]
tarantool 2.0 + tarantool-python master: make test passed.

**Comment by racktear** [comment]
I've tried to dig further and this only reproduces in python3 and tarantool 1.10.0

**Comment by racktear** [comment]
The reason is this line:

```python
(product, _, tail) = str(greeting_buf)[0:63].partition(' ')
```

in python3, taking `str()` of a binary string makes it look like `"b'original_string'"`
