### ISSUE TITLE
caniusepython3 keeps saying tarantool is not Python 3 compatible

### ISSUE THREAD

**Issue by pcdinh** [tarantool/tarantool-python#103]
Please check https://caniusepython3.com/project/tarantool

It looks like you need to change setup.py to signal Python 3 support: https://github.com/brettcannon/caniusepython3

Thanks

**Comment by Totktonada** [comment]
Now looks good on caniusepython3, despite that setup.py has no `Programming Language :: Python :: 3`.

**Comment by Totktonada** [comment]
Now it gives me 504 Gateway Time-out. But when I did check the webpage the last time it says that Python 3 is supported. I think we'll close the issue.
