### ISSUE TITLE
Replace inconnect flag with something more appropriate

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool-python#108]
For example, create a lock object for controlling recursion and add wrap locking/unlocking into decorator around `connect`/`opt_reconnect`

**Comment by Totktonada** [comment]
It is unclear what kind of problem it tries to solve. The code suggests that it is about synchronization, but readme clearly states that a connection can not be shared between different threads. If it is something Windows-related, we need to create a test case.

It looks now that, if we'll just remove this flag, things will work well.
