### ISSUE TITLE
Function sys.version_info.minor is available starting from py 2.7

### ISSUE THREAD

**Issue by gostkov** [tarantool/tarantool-python#143]
Function sys.version_info.minor is available starting from py 2.7. In 2.6.6 not available.
For more support, can you replace sys.version_info.major (minor) 

```
sys.version_info[0] #sys.version_info.major
# and
sys.version_info[0] #sys.version_info.minor

```

Thank you.

**Comment by Totktonada** [comment]
I doubt that Python 2.6 is interested for community now. We'll not pay our time to support Python 2.6, will not add testing against Python 2.6 and so I don't see a reason to attempt to support it in some particular place: we can break it in another place in some further change.

Anyway, if you're interested to get it fixed, feel free to send a pull request. It is okay to include if it will not break anything.

**Comment by DifferentialOrange** [comment]
Python 2 support is dropped since 0.8.0
