### ISSUE TITLE
Execute Sql Support

### ISSUE THREAD

**Issue by enescaglar** [tarantool/tarantool-python#159]
Hi,

Does this library support executing SQL? I can't find it but just wanted to clarify.

Thanks.

**Comment by Totktonada** [comment]
AFAIK, @robinhood23rus and @artembo did some work in this direction. Maybe they will update us with current status.

**Comment by knazarov** [comment]
@artembo has implemented python-compatible DB API. He will create a pull-request eventually. 
He did it in order to add support for Tarantool in Django ORM (which by the way worked out well enough)

**Comment by enescaglar** [comment]
Thank you all for your answers. It's good to hear, changes will be merged soon.
