### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by a1tus** [tarantool/tarantool-python#183]
Hello.

Are you planning to make a release with new features since 0.6.6?

In our case, we have to use commit id coz of breaking changes in msgpack 1.0.0.

**Comment by Totktonada** [comment]
Sure.

**Comment by Totktonada** [comment]
tarantool 0.7.1 was released.

**Comment by Totktonada** [comment]
That was my mistake: I released [0.7.0](https://github.com/tarantool/tarantool-python/releases/tag/0.7.0) first, but then I found that it depends on `msgpack-python` (the old library name). So, I yanked the release on PyPI (AFAIU pip will not install it if this version is not requested explicitly) and released [0.7.1](https://github.com/tarantool/tarantool-python/releases/tag/0.7.1) with the correct dependency. Sorry for possible inconvenience.

**Comment by a1tus** [comment]
@Totktonada great, thank you.
