### ISSUE TITLE
Is there a way to add custom type by myself? For example, uuid

### ISSUE THREAD

**Issue by TvoroG** [tarantool/tarantool-python#191]
Hey! Thanks for the work!

I cannot figure out the right way to add custom type. `msgpack-python` supports ext type by `ext_hook` and `default` arguments to `Packer` and `Unpacker`, but we cannot pass them through tarantool connection. Am I wrong?

**Comment by Totktonada** [comment]
It seems, you are right. I would make it extensible, more or less in the spirit of PR #190. I'll consider this issue as the feature request.
