### ISSUE TITLE
Support new authentication mechanisms

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/tarantool-python#269]
New authentication mechanisms are in design for next Tarantool versions. After the release of this feature, we must support it.

**Comment by DifferentialOrange** [comment]
Design document (private): https://www.notion.so/tarantool/Authentication-methods-908501aa74834bdea70c384d6df97105

**Comment by LeonidVas** [comment]
To be implemented in the EE-version of the connector.

**Comment by DifferentialOrange** [comment]
So should we close the issue here?

**Comment by LeonidVas** [comment]
The bosses turn the wheel one more time. We implement this feature here.
