### ISSUE TITLE
Make pandas dependency optional

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/tarantool-python#290]
There are a lot of projects with Tarantool+Python which are not interested in using datetimes (for example, all projects with Tarantool 2.8 and older). They are still obliged to install `pandas` and `pytz`, both are rather heavy. Users ask to make this dependency optional.

It seems that Python package mechanism for providing optional dependencies is ["extras"](https://peps.python.org/pep-0440/). We also shouldn't forget to make deb and rpm package dependencies optional.

This change is a **breaking** one, since user would need to change their setup process if they want to work with datetimes.

We may start throwing errors for datetimes in msgpack if we cannot parse them or return some dictionaries/tuples with raw binary data.

**Comment by LeonidVas** [comment]
Talked, it looks like it makes sense to do a split into 2 packages and the default should be a package with support for all types on board.
But there's a lot to think about.
