### ISSUE TITLE
Add tarantool-python to Tarantool buildbot

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool-python#36]
+ Write RPM specs/DEB rules and push they to the repository. Please use package name that confirms official distributive naming conventions (e.g. tarantool-python or python-tarantool)
+ Add this project to build bot (http://build.tarantool.org/)
+ Check that module build and can be installed from tarantool.org repository

**Comment by Sulverus** [comment]
Done. Awaiting for check.
http://master.farm.tarantool.org/builders/Python%20tarantool%20DEB
http://master.farm.tarantool.org/builders/Python%20tarantool%20RPM
