### ISSUE TITLE
Wrong Space.update() examples in the manual

### ISSUE THREAD

**Issue by akopytov** [tarantool/tarantool-python#48]
All Space.update() examples in the manual use the following syntax:
```
Space.update(key, [(fieldno, op, value)])
```

However, the actual syntax expected by the driver is:
```
Space.update(key, [(op, fieldno, value)])
```

**Comment by xHasKx** [comment]
Fixing in pull request https://github.com/tarantool/tarantool-python/pull/52

**Comment by bigbes** [comment]
Superseeded by #67
