### ISSUE TITLE
socket.error after tarantool restart

### ISSUE THREAD

**Issue by bekbulatov** [tarantool/tarantool-python#57]
I'm using tarantool 1.5 with stable branch (0.3.6 version) of python driver.
After tarantool restart I got `Connection reset by peer` error in line https://github.com/tarantool/tarantool-python/blob/stable/src/tarantool/connection.py#L150 and `Broken pipe` in line https://github.com/tarantool/tarantool-python/blob/stable/src/tarantool/connection.py#L172
Reconnect with `connection.connect()` helps, but it's better to fix in driver.
Tried to do it by myself but I'm confused with libc magic and `self._recv` https://github.com/tarantool/tarantool-python/blob/stable/src/tarantool/connection.py#L189 which always is None

**Comment by bekbulatov** [comment]
`if self._recv == None` was added in 0.3.6 
0.3.5 seems to work fine

**Comment by bigbes** [comment]
If it's related to Windows, then it must be fixed in the latest master. sorry for long response.
