### ISSUE TITLE
New manual for 0.5+ version driver

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool-python#67]
Our quick-start.{ru/en}.rst and guide.{ru/en}.rst are obsolete.

Superseeds #49 and #48.

**Comment by Totktonada** [comment]
Several points to consider:

* We should revisit both guides and API docs.
* The task requires some level of Python understanding, reading throught the code and tests and manual testing.
* The docs should look nice on [readthedocs](https://tarantool-python.readthedocs.io/en/latest/).

**Comment by DifferentialOrange** [comment]
One more crucial point: application developer's journey is incomprehensible. What's the life cycle? How should I process requests in code and its errors? Even tests are not useful due to `assertSequenceEqual`
