### ISSUE TITLE
Unexpected behaviour in connection.call

### ISSUE THREAD

**Issue by zevlg** [tarantool/tarantool-python#73]
With tarantool 1.5.5 on server-side if I call:

```python
    conn.call("box.auto_increment", 0, "val1", "fld2")
```

I'll get the error:

```
  Lua error: [string "-- misc.lua (internal file)..."]:57: attempt to index a nil value
```

However if I stringify my space number, then everything is ok:

```python
    conn.call("box.auto_increment", "0", "val1", "fld2")
    ==> [('\xbd\x00\x00\x00', 'val1', 'fld2')]
```

It is quite weird that one should specify space number as string value

**Comment by bigbes** [comment]
It's weird, but this is the behaviour of 1.5 protocol. In 1.6 types were added to protocol (using msgpack), so it mustn't be a problem.
