### ISSUE TITLE
Broken iterator types for Connection.select

### ISSUE THREAD

**Issue by gafusss** [tarantool/tarantool-python#77]
Commit eca0e484b646a99c93cc5017156b50ba64a63d05 fixing #76 breaks iterators for select, always setting the iterator to either _ALL or _EQ
```python
if iterator_type == None and \
           (key == None or (isinstance(key, (list, tuple)) and len(key) == 0)):
               iterator_type = ITERATOR_ALL
        else:
            iterator_type = ITERATOR_EQ
```

**Comment by bigbes** [comment]
Thank you! This mistake was made as a result of haste:) thank you very much for your time!
