### ISSUE TITLE
FTBFS on Fedora 24/25

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool-python#85]
https://travis-ci.org/tarantool/tarantool-python/jobs/205775358#L506

```
+ exit 0
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.QkO7ao
+ umask 022
+ cd /build/usr/src/debug
+ '[' /build/BUILDROOT/tarantool-python-0.5.4-24.el7.centos.x86_64 '!=' / ']'
+ rm -rf /build/BUILDROOT/tarantool-python-0.5.4-24.el7.centos.x86_64
++ dirname /build/BUILDROOT/tarantool-python-0.5.4-24.el7.centos.x86_64
+ mkdir -p /build/BUILDROOT
+ mkdir /build/BUILDROOT/tarantool-python-0.5.4-24.el7.centos.x86_64
+ cd tarantool-python-0.5.4
+ python setup.py install --single-version-externally-managed -O1 --root=/build/BUILDROOT/tarantool-python-0.5.4-24.el7.centos.x86_64 --record=INSTALLED_FILES
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
error: option --single-version-externally-managed not recognized
error: Bad exit status from /var/tmp/rpm-tmp.QkO7ao (%install)
```

**Comment by bigbes** [comment]
Probably this should help:

> --single-version-externally-managed is an option used for Python packages instructing the setuptools module to create a Python package which can be easily managed by the host's package manager if needed, like Yum or Apt.
> 
> If you're seeing this message, you may have an old version of setuptools or Python. Try using Distribute, which is a newer version of setuptools and is backwards compatible. These packages may expect that you have it already.
> 
> https://pypi.python.org/pypi/distribute
> 
> Edit: At this point, distribute has been merged into the main setuptools project. Just install the latest version of setuptools. As @wynemo indicated, you may wish to use the --egg option instead, as it's more appropriate for those doing manual installations where you're not intending to create a system package for distribution.
from: https://stackoverflow.com/a/15258644/1277198
